[bugfix]  semantic error TS2322: Type { src: string; alt: string; layout: string; } is not assignable to type DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>. Property layout does not exist on DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>